[2025-05-28T08:35:58.028+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-28T08:35:58.109+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: image_processing_per_file_v2.preprocess_group.img_preprocess_task manual__2025-05-28T08:35:51.432802+00:00 map_index=3 [queued]>
[2025-05-28T08:35:58.135+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: image_processing_per_file_v2.preprocess_group.img_preprocess_task manual__2025-05-28T08:35:51.432802+00:00 map_index=3 [queued]>
[2025-05-28T08:35:58.136+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-28T08:35:58.180+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_group.img_preprocess_task> on 2025-05-28 08:35:51.432802+00:00
[2025-05-28T08:35:58.210+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=85490) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-28T08:35:58.215+0000] {standard_task_runner.py:72} INFO - Started process 85506 to run task
[2025-05-28T08:35:58.229+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'image_processing_per_file_v2', 'preprocess_group.img_preprocess_task', 'manual__2025-05-28T08:35:51.432802+00:00', '--job-id', '253', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp2c6lui8o', '--map-index', '3']
[2025-05-28T08:35:58.232+0000] {standard_task_runner.py:105} INFO - Job 253: Subtask preprocess_group.img_preprocess_task
[2025-05-28T08:35:58.458+0000] {task_command.py:467} INFO - Running <TaskInstance: image_processing_per_file_v2.preprocess_group.img_preprocess_task manual__2025-05-28T08:35:51.432802+00:00 map_index=3 [running]> on host 293edbf976f9
[2025-05-28T08:35:58.815+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='image_processing_per_file_v2' AIRFLOW_CTX_TASK_ID='preprocess_group.img_preprocess_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T08:35:51.432802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T08:35:51.432802+00:00'
[2025-05-28T08:35:58.821+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-28T08:35:58.823+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-28T08:35:58.831+0000] {logging_mixin.py:190} INFO - Current task name:preprocess_group.img_preprocess_task state:running start_date:2025-05-28 08:35:58.110572+00:00
[2025-05-28T08:35:58.836+0000] {logging_mixin.py:190} INFO - Dag name:image_processing_per_file_v2 and current dag run status:running
[2025-05-28T08:35:58.837+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-28T08:35:58.839+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/PIL/Image.py", line 3511, in open
    fp.seek(0)
    ^^^^^^^
AttributeError: 'list' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/img_preprocess_util.py", line 22, in img_preprocess_task
    input = type_convert_util.convert_type(output,before_output_type,function_info["input_type"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/type_convert_util.py", line 21, in convert_type
    return _call_with_compatible_args(func_info, data, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/type_convert_util.py", line 185, in _call_with_compatible_args
    return f(data, **call_args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/type_convert_util.py", line 32, in file_to_np_rgb
    img = Image.open(file_path)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/PIL/Image.py", line 3513, in open
    fp = io.BytesIO(fp.read())
                    ^^^^^^^
AttributeError: 'list' object has no attribute 'read'
[2025-05-28T08:35:58.909+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-28T08:35:58.909+0000] {logging_mixin.py:190} INFO - Task start:2025-05-28 08:35:58.110572+00:00 end:2025-05-28 08:35:58.908478+00:00 duration:0.797906
[2025-05-28T08:35:58.910+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): preprocess_group.img_preprocess_task> dag:<DAG: image_processing_per_file_v2> dagrun:<DagRun image_processing_per_file_v2 @ 2025-05-28 08:35:51.432802+00:00: manual__2025-05-28T08:35:51.432802+00:00, state:running, queued_at: 2025-05-28 08:35:51.445762+00:00. externally triggered: True>
[2025-05-28T08:35:58.911+0000] {logging_mixin.py:190} INFO - Failure caused by 'list' object has no attribute 'read'
[2025-05-28T08:35:58.916+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=image_processing_per_file_v2, task_id=preprocess_group.img_preprocess_task, run_id=manual__2025-05-28T08:35:51.432802+00:00, map_index=3, execution_date=20250528T083551, start_date=20250528T083558, end_date=20250528T083558
[2025-05-28T08:35:59.044+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-28T08:35:59.045+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 253 for task preprocess_group.img_preprocess_task ('list' object has no attribute 'read'; 85506)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/PIL/Image.py", line 3511, in open
    fp.seek(0)
    ^^^^^^^
AttributeError: 'list' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/img_preprocess_util.py", line 22, in img_preprocess_task
    input = type_convert_util.convert_type(output,before_output_type,function_info["input_type"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/type_convert_util.py", line 21, in convert_type
    return _call_with_compatible_args(func_info, data, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/type_convert_util.py", line 185, in _call_with_compatible_args
    return f(data, **call_args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/type_convert_util.py", line 32, in file_to_np_rgb
    img = Image.open(file_path)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/PIL/Image.py", line 3513, in open
    fp = io.BytesIO(fp.read())
                    ^^^^^^^
AttributeError: 'list' object has no attribute 'read'
[2025-05-28T08:35:59.134+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-28T08:35:59.447+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-28T08:35:59.472+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
