[2025-05-27T09:15:07.328+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-27T09:15:07.883+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: image_processing_per_file_v2.preprocess_group.grayscale_task manual__2025-05-27T08:58:50.827042+00:00 map_index=360 [queued]>
[2025-05-27T09:15:08.583+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: image_processing_per_file_v2.preprocess_group.grayscale_task manual__2025-05-27T08:58:50.827042+00:00 map_index=360 [queued]>
[2025-05-27T09:15:08.593+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-27T09:15:08.640+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_group.grayscale_task> on 2025-05-27 08:58:50.827042+00:00
[2025-05-27T09:15:08.697+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=41017) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-27T09:15:08.705+0000] {standard_task_runner.py:72} INFO - Started process 41127 to run task
[2025-05-27T09:15:08.743+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'image_processing_per_file_v2', 'preprocess_group.grayscale_task', 'manual__2025-05-27T08:58:50.827042+00:00', '--job-id', '1686', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpp5v5938u', '--map-index', '360']
[2025-05-27T09:15:08.763+0000] {standard_task_runner.py:105} INFO - Job 1686: Subtask preprocess_group.grayscale_task
[2025-05-27T09:15:09.120+0000] {task_command.py:467} INFO - Running <TaskInstance: image_processing_per_file_v2.preprocess_group.grayscale_task manual__2025-05-27T08:58:50.827042+00:00 map_index=360 [running]> on host d13339a4a574
[2025-05-27T09:15:09.571+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='image_processing_per_file_v2' AIRFLOW_CTX_TASK_ID='preprocess_group.grayscale_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T08:58:50.827042+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T08:58:50.827042+00:00'
[2025-05-27T09:15:09.579+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-27T09:15:09.579+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-27T09:15:09.580+0000] {logging_mixin.py:190} INFO - Current task name:preprocess_group.grayscale_task state:running start_date:2025-05-27 09:15:07.892910+00:00
[2025-05-27T09:15:09.581+0000] {logging_mixin.py:190} INFO - Dag name:image_processing_per_file_v2 and current dag run status:running
[2025-05-27T09:15:09.581+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-27T09:15:09.582+0000] {logging_mixin.py:190} INFO - ----------file_path /opt/***/data/upload/test/스크린샷 2025-05-23 143432 - 복사본 - 복사본 - 복사본 - 복사본 (2).png
[2025-05-27T09:15:09.584+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/img_preprocess_util.py", line 9, in grayscale_task
    img = Image.open(file_path)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/PIL/Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/upload/test/스크린샷 2025-05-23 143432 - 복사본 - 복사본 - 복사본 - 복사본 (2).png'
[2025-05-27T09:15:09.676+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-27T09:15:09.684+0000] {logging_mixin.py:190} INFO - Task start:2025-05-27 09:15:07.892910+00:00 end:2025-05-27 09:15:09.659981+00:00 duration:1.767071
[2025-05-27T09:15:09.689+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): preprocess_group.grayscale_task> dag:<DAG: image_processing_per_file_v2> dagrun:<DagRun image_processing_per_file_v2 @ 2025-05-27 08:58:50.827042+00:00: manual__2025-05-27T08:58:50.827042+00:00, state:running, queued_at: 2025-05-27 08:58:50.983771+00:00. externally triggered: True>
[2025-05-27T09:15:09.691+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/data/upload/test/스크린샷 2025-05-23 143432 - 복사본 - 복사본 - 복사본 - 복사본 (2).png'
[2025-05-27T09:15:09.692+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=image_processing_per_file_v2, task_id=preprocess_group.grayscale_task, run_id=manual__2025-05-27T08:58:50.827042+00:00, map_index=360, execution_date=20250527T085850, start_date=20250527T091507, end_date=20250527T091509
[2025-05-27T09:15:09.793+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-27T09:15:09.809+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1686 for task preprocess_group.grayscale_task ([Errno 2] No such file or directory: '/opt/airflow/data/upload/test/스크린샷 2025-05-23 143432 - 복사본 - 복사본 - 복사본 - 복사본 (2).png'; 41127)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/img_preprocess_util.py", line 9, in grayscale_task
    img = Image.open(file_path)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/PIL/Image.py", line 3505, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/upload/test/스크린샷 2025-05-23 143432 - 복사본 - 복사본 - 복사본 - 복사본 (2).png'
[2025-05-27T09:15:10.158+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-27T09:15:10.218+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
